services:
  emergencias-postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emergencias-postgres
    environment:
      POSTGRES_DB: emergencias
      POSTGRES_USER: emergencias
      POSTGRES_PASSWORD: emergencias
    ports:
      - "55434:5432"
    volumes:
      - emergencias_pg_data:/var/lib/postgresql/data

volumes:
  emergencias_pg_data:
